name: tinyq
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  google_fonts: ^6.2.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  firebase_auth: ^5.5.0
  firebase_core: ^3.12.0
  cloud_firestore: ^5.6.4 
  firebase_storage: ^12.4.3  

  firebase_app_check: ^0.3.2+4

  uuid: ^4.0.0  
  image_picker: ^1.0.4
  cached_network_image: ^3.4.1

  date_format: ^2.0.9

  http: ^1.3.0
  intl: ^0.20.2
  url_launcher: ^6.3.1

  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
   android: true
   ios: true
   image_path: "assets/icon/1024.png"
   android_icon: true
   ios_icon: true
   adaptive_icon:
    android: true
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
          weight: 400  # ควรเป็น 400 (Regular)

    - family: Crimson
      fonts:
        - asset:  assets/fonts/CrimsonText-Regular.ttf
          weight: 400
        - asset:  assets/fonts/CrimsonText-Bold.ttf
          weight: 700
        - asset:  assets/fonts/CrimsonText-SemiBold.ttf
          weight: 600
        - asset:  assets/fonts/CrimsonText-BoldItalic.ttf
          weight: 700
        - asset:  assets/fonts/CrimsonText-Italic.ttf
          weight: 400